### ISSUE TITLE
Small typo in tutorial

### ISSUE THREAD

**Issue by edoarad** [iarai/science4cast#2]
> First, get the data from the [IARAI cloud](https://cloud.iarai.ac.at/index.php/s/iTx3bXgMdwsngPn). It contains three files:
> - **TrainSet2014_3.pkl:** (33 MB) Semantic network until 2014, and list of unconnected vertex-pairs that can be predicted for training the neural network.
> - **TrainSet2014_3_solution.pkl**: (0.5 MB) Solution of whether the unconnected vertex pair from 2014 has been connected by 2017.
> - **CompetitionSet2017_3.pkl**: (95 MB) Semantic network until **2014**, and list of unconnected vertex-pairs that should be predicted for the evaluation.

That last line should be the Semantic network until **2017**, I think.

**Comment by MarioKrenn6240** [comment]
Thanks for reporting, and sorry that this took so long, i fixed the typo now.
