### ISSUE TITLE
About test data (2017-2020) release

### ISSUE THREAD

**Issue by phucdoitoan** [iarai/science4cast#5]
Thank you for organizing this competition.
I am very much looking forward to the youtube video of the workshop talks.

About the data from 2017-2020, do you have plan to release these data as well?

**Comment by MarioKrenn6240** [comment]
Hi @phucdoitoan - Yes both the videos and dataset will be released. Videos in the beginning of january. For the dataset we write right now a paper with participants, so that will also go public some day early 2022.

best regards,
Mario

**Comment by phucdoitoan** [comment]
That's great! I am looking forward to the paper!
